awarephish/awarephish/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('quiz.urls')),
    path('admin/', admin.site.urls),
    
]

awarephish/quiz/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('',views.redir, name='redir'),
    path('index/', views.index,name='index'),
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('conseils/', views.conseils, name='conseils'),
    path('account/', views.account, name="account"),
    path('level-quiz/', views.level_quiz, name="level-quiz"),
    path('result/', views.result, name="result"),
    path('phishquiz/', views.phishquiz, name="phishquiz"),
    path('account/progres', views.progress, name="progress"),
    path('resultquiz/', views.resultquiz, name="resultquiz"),
    path('account/homework/', views.homework, name='homework'),
    path('accout/viewprogres/', views.view_progress, name='view-progress'),
    path('account/settings', views.parametre, name="parametre"),
]

awarephish/quiz/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Question(models.Model):
    type_question = models.CharField('Type de question', max_length=100)
    question_text = models.TextField(max_length=700)
    difficulty = models.CharField('Difficulté', max_length=10)
    note = models.SmallIntegerField()
    image = models.ImageField(upload_to='questions', null=True, blank=True)

    def __str__(self):
        return f"Question {self.id}"

class Reponses(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    wrong_answers = models.CharField('Réponses Incorrectes', max_length=400, null=True, blank=True)
    correct_answer = models.CharField('Réponses correctes', max_length=400, null=True, blank=True)

class Devoir(models.Model):
    type_devoir = models.CharField("Type de devoir", max_length=100)
    difficulty_devoir = models.CharField("niveau du devoir",max_length=50)
    duree = models.IntegerField("durée estimée (min)")
    contenu = models.FileField(upload_to='devoirs/%Y/%m/%d/',null=True,blank=True)
    texte = models.TextField("Texte", max_length=600, null=True, blank=True)

    def __str__(self):
        return f"Devoir {self.difficulty_devoir} : type {self.type_devoir}"


class Utilisateur(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    score_actuel = models.IntegerField(default=0)
    niveau_actuel = models.CharField('Niveau', max_length=50, default='Niveau 1')
    homework = models.ManyToManyField(Devoir,blank=True)
    total_reponse = models.IntegerField("nombre total de reponse", default=0)
    total_reponse_correctes = models.IntegerField("nombre de total de reponse correcte", default=0)
    def __str__(self):
        return str(self.user)

class Quiztest(models.Model): # test in mcd
    difficulty_test = models.CharField("Niveau du test", max_length=50)
    questions = models.ManyToManyField(Question)
    users = models.ManyToManyField(Utilisateur, blank=True)

    def __str__(self):
        return f"Quiz {self.id}"

class Progres(models.Model):
    user = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    date_test = models.DateTimeField("Date de test")
    score_test = models.IntegerField()

    def __str__(self):
        return str(self.user)



    

awarephish/quiz/forms.py
from django import forms
from .models import Utilisateur,User
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

class SignupForm(forms.Form):
    username = forms.CharField(max_length=150, label='Nom d\'utilisateur', widget=forms.TextInput(attrs={'placeholder':'Entrez le nom d\'utilisateur'}))
    password1 = forms.CharField(label='Mot de passe', widget=forms.PasswordInput(
            attrs={'placeholder':'Entrez votre mot de passe',
            'pattern':r"(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}", 
            'title':"Doit contenir au moins un nombre, une lettre majuscule et une lettre minuscule, et au moins 8 caractères"}))
    password2 = forms.CharField(label='Confirmer le mot de passe', widget=forms.PasswordInput(attrs={'placeholder':'Confirmer votre mot de passe'}))
    email = forms.EmailField(label='Adresse Email',widget=forms.EmailInput(attrs={'placeholder':'Entrez votre email'}))

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = Utilisateur.user.get_queryset().filter(username=username)
        if r.count():
            raise ValidationError("Nom d'utilisateur déjà pris")
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = Utilisateur.user.get_queryset().filter(email=email)
        if r.count():
            raise ValidationError("Cette adresse existe déjà")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Les mots de passes ne correspondent pas")
        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

class SigninForm(AuthenticationForm):
    username = forms.CharField(max_length=150, label='Nom d\'utilisateur', widget=forms.TextInput(attrs={'placeholder':'Entrez le nom d\'utilisateur'}))
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput(attrs={'placeholder':'Entrez votre mot de passe'}))

    error_messages = {
        'invalid_login': ("Nom d`'utilisateur ou mot de passe incorrect"),
    }

class ChangePass(PasswordChangeForm):
    new_password1 = forms.CharField(
        label="Nouveau mot de passe",
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password','placeholder':'Entrez votre nouveau mot de passe'}),
        strip=False,
        help_text="Au minimum 8 caractères.\nDoit contenir au moins un caractère numérique, une majuscule et un symbole",
    )
    new_password2 = forms.CharField(
        label="Confirmation du nouveau mot de passe",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password','placeholder':'Confirmer votre nouveau mot de passe'}),
    )
    old_password = forms.CharField(
        label="Mot de passe actuel",
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True,'placeholder':'Entrer votre mot de passe actuel'})
    )

    error_messages = {
        'password_mismatch':('Les mots de passe ne correspondent pas'),
        'password_incorrect':("Votre ancien mot de passe est incorrect"),
    }

class ChangeMail(forms.Form):
    error_messages={
        'email_inuse': "Cette adresse est déjà enregistrée.",
        'password_incorrect': 'Mot de passe incorrect'
}

    old_mail = forms.EmailField(label='Adresse Email actuelle',widget=forms.EmailInput(attrs={'placeholder':'Entrer votre adresse actuelle'}))
    new_email = forms.EmailField(label='Nouvelle adresse Email',widget=forms.EmailInput(attrs={'placeholder':'Entrez votre nouvelle adresse email'}))
    current_password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={'placeholder':'entrez votre mot de passe pour confirmer'}),required=True)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangeMail, self).__init__(*args, **kwargs)
    
    def clean_current_password(self):
        """
        Validates that the password field is correct.
        """
        current_password = self.cleaned_data["current_password"]
        if not self.user.check_password(current_password):
            raise forms.ValidationError(self.error_messages['password_incorrect'], code='password_incorrect',)
        return current_password
    
    def clean_new_email(self):
        """
        Prevents an e-mail address that is already registered from being registered by a different user.
        """
        email = self.cleaned_data.get('new_email')
        if Utilisateur.user.get_queryset().filter(email=email).count() > 0:
            raise forms.ValidationError(self.error_messages['email_inuse'], code='email_inuse',)
        return email

    def clean_old_mail(self):
        return self.cleaned_data['old_mail']

    def save(self, commit=True):
        self.user.email=self.cleaned_data["new_email"]
        self.user.save()
        return self.user

awarephish/quiz/views.py
import random
import datetime

from statistics import mean, StatisticsError

from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.utils import timezone

from .forms import SignupForm, SigninForm, ChangePass, ChangeMail
from .models import Utilisateur, Question, Progres, Quiztest, Devoir
from .utils import evaluate_level, get_user_answers, message_level, get_nextlevel_score, evaluate_level_test
# Create your views here.

def redir(request):
    return redirect('/index/')

def index(request):
    return render(request,"quiz/index.html")

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            Utilisateur(user=user, score_actuel=0).save()
            login(request, user)
            return redirect('/index/')
    else:
        form = SignupForm()
    return render(request,'quiz/signup.html/',{'form':form})

def signin(request):
    if request.method == 'POST':
        form = SigninForm(data=request.POST)
        if form.is_valid():
            user = authenticate(
                    username= form.cleaned_data['username'],
                    password=form.cleaned_data['password'])
            login(request, user)
            return redirect('/index/')
    else:
        form = SigninForm()
    return render(request, 'quiz/signin.html',{'form':form})


@login_required
def signout(request):
    logout(request)
    return redirect('/index/')

def conseils(request):
    return render(request,'quiz/conseil.html')

def account(request):
    user = get_object_or_404(Utilisateur, user=request.user)
    try:
        ratio = round((user.total_reponse_correctes/user.total_reponse)*100,2)
        
    except ZeroDivisionError:
        ratio = 0
    finally:
        try:
            moyenne = round(mean(p.score_test for p in user.progres_set.all()),2)
        except StatisticsError:
            moyenne = 0
        return render(request,'quiz/account.html',{'score':user.score_actuel,
                                                    'users':user,
                                                    'next':get_nextlevel_score(user.niveau_actuel),
                                                    'progress':round((user.score_actuel/get_nextlevel_score(user.niveau_actuel))*100,2),
                                                    'remainder':get_nextlevel_score(user.niveau_actuel) - user.score_actuel,
                                                    'ratio':ratio,
                                                    'mean': moyenne,
                                                    })

def level_quiz(request):
    r=[]
    for level in ["Niveau 1","Niveau 2", "Niveau 3"]:
        r += random.sample(
                set(Question.objects.filter(difficulty=level)),
                2)
    phishset = r.copy()
    quiz = {question : {reponse : reponse.correct_answer for reponse in question.reponses_set.all()} for question in phishset}
    return render(request,'quiz/level-quiz.html',{'quiz':quiz})

def result(request):
    user_answers = get_user_answers(request)
    question_ids=[int(x) for x in request.POST.get('id').split(",")[:-1] ]
    score=0
    scoretest=0
    for questid in question_ids:
        question = get_object_or_404(Question, pk=questid)
        answer_score = question.note / question.reponses_set.filter(correct_answer__isnull=False).count()
        scoretest += question.note
        user_answers_copy = user_answers.copy()

        for answer in user_answers_copy:
            if question.reponses_set.filter(Q(wrong_answers=answer) | Q(correct_answer=answer)):
                user_answers.remove(answer)
                if question.reponses_set.filter(correct_answer=answer):
                    score += answer_score
                else:
                    score -= answer_score

    score = round(max((score/scoretest)*10, 0),1)
    level = evaluate_level_test(score)
    message = message_level(level)
    return JsonResponse({'status':1,'score':f"{score}/10", 'level':level,'message':message})

@login_required(login_url='/signin/')
def phishquiz(request):
    user = get_object_or_404(Utilisateur, user=request.user)
    quiztest = random.choice(Quiztest.objects.filter(difficulty_test=user.niveau_actuel).exclude(users=user))
    quiz = {quest : [rep for rep in quest.reponses_set.all()] for quest in quiztest.questions.all()}
    return render(request,'quiz/phishing-quiz.html',{'quiz':quiz, 'quiztest':quiztest})

def resultquiz(request):
    user = get_object_or_404(Utilisateur, user=request.user)
    quiztest = get_object_or_404(Quiztest, pk=int(request.POST.get('id')))
    quiztest.users.set([user])
    quiztest.save()

    questions = quiztest.questions.all()
    user_answers = get_user_answers(request)
    score = 0
    scoretest = 0
    nbr_reponse, nbr_reponse_correcte = 0,0

    for question in questions:
        answer_score = question.note / question.reponses_set.filter(correct_answer__isnull=False).count()
        scoretest += question.note
        user_answers_copy = user_answers.copy()
        for answer in user_answers_copy:
            if question.reponses_set.filter(Q(wrong_answers=answer) | Q(correct_answer=answer)):
                user_answers.remove(answer)
                if question.reponses_set.filter(correct_answer=answer):
                    score += answer_score
                    nbr_reponse_correcte += 1
                    nbr_reponse += 1
                elif answer == "Je ne sais pas":
                    nbr_reponse += 1
                    continue
                else:
                    nbr_reponse += 1
                    score -= answer_score
    coef = get_nextlevel_score(user.niveau_actuel)
    
    score = max(round(score,2), 0)
    user.score_actuel = min(round(user.score_actuel + score, 2),300)
    user.total_reponse += nbr_reponse
    user.total_reponse_correctes += nbr_reponse_correcte

    user.niveau_actuel = evaluate_level(user.score_actuel)
    try:
        homeworks = [random.choice(Devoir.objects.filter(difficulty_devoir=user.niveau_actuel,type_devoir=typ).exclude(utilisateur=user))for typ in ["video","texte"]]
    except IndexError:
        homeworks=[]

    user.homework.set(homeworks+list(user.homework.all()))
    
    user.progres_set.create(date_test=timezone.now(), score_test=score)
    user.save()
    next_level = get_nextlevel_score(user.niveau_actuel)

    return JsonResponse({'status':1, 'result':score,'actual':user.score_actuel , 'level':user.niveau_actuel,'next':next_level})

def view_progress(request):
    user = get_object_or_404(Utilisateur, user=request.user)
    prog = { 
            'x':[p.date_test for p in user.progres_set.all()],
            'y': [p.score_test for p in user.progres_set.all()],
    }
    return JsonResponse({'status':1, 'progress':prog})

@login_required
def homework(request):
    user = get_object_or_404(Utilisateur, user=request.user)
    devoirs = user.homework.all()
    return render(request,'quiz/homework.html',{'devoir':devoirs})

@login_required
def progress(request):
    return render(request,"quiz/progress.html")


@login_required
def parametre(request):
    pass_form = ChangePass(user=request.user)
    mail_form = ChangeMail(user=request.user,initial={'old_mail':request.user.email})
    if request.method == 'POST':
        if "pass_change" in request.POST:
            pass_form = ChangePass(user=request.user, data=request.POST)
            if pass_form.is_valid():
                pass_form.save()
                update_session_auth_hash(request, pass_form.user)
                messages.success(request, 'Votre mot de passe a été changé avec succès')
        elif "mail_change" in request.POST:
            mail_form = ChangeMail(user=request.user, data=request.POST)
            if mail_form.is_valid():
                mail_form.save()
                messages.success(request, 'Votre adresse mail a été modifiée avec succès')
    return render(request, 'quiz/parametres.html', {'passform':pass_form, 'mailform':mail_form})

awarephish/quiz/templates/quiz/parametres.html
{% load static%}<!DOCTYPE HTML>
<html>
	<head>
		<title>Paramètres</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<noscript>
			<link rel="stylesheet" href="css/skel-noscript.css" />
			<link rel="stylesheet" href="css/style.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
	</head>
	<body>
		<div id="wrapper">
			
			<!-- Header -->
			<div id="header">
				<div class="container"> 
					
					<!-- Logo -->
					<div id="logo">
						<h1><a href="{% url 'index'%}">AwarePhish</a></h1>
						<span class="font-weight-bolder">Pour ne pas tomber dans le piège !</span>
					</div>
					
					<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="{% url 'index'%}">page d'accueil</a></li>
							<li><a href="{% url 'conseils' %}">conseils</a></li>
							<li><a href={% if user.is_authenticated %}"{% url 'phishquiz' %}"{% else %}{% url 'signin' %} onclick="return confirm('Vous devez être connecté')"{% endif%}>testez-vous</a></li>
							<li class="active">
								{% if user.is_authenticated %}
									<a href="{% url 'account' %}">Compte</a></li>
								{% else %}
									<a href="{% url 'signup' %}">S'inscrire</a>
								{% endif%}
							</li>
							<li>
								{% if user.is_authenticated %}
									<a href="{% url 'signout' %}">Se déconnecter</a>
								{% else %}
									<a href="{% url 'signin' %}">Se connecter</a>
								{%endif%}
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /Header -->
			
			<div id="page">
				<div class="container">
					<div class="row">
						<div class="1u">
							<section id="box1">.</section>
						</div>
						<div class="2u">
							<section id="sidebar1" >
								<header>
									<h2>compte</h2>
								</header>
								<div class="btn-group-vertical">
									<a class="btn btn-dark" href="{% url 'account' %}">Infos</a>
									<a class="btn btn-dark" href="{% url 'homework' %}">Devoirs</a>
									<a class="btn btn-dark " href="{% url 'progress' %}">Progrès</a>
									<a class="btn btn-info active " href="{%url 'parametre'%}">Paramètres</a>
									
								</div>
							</section>
						</div>	
						
						<div class="9u skel-cell-important">
							<section id="content">
								{% if messages %}
								<ul class="messages bg-success text-dark font-weight-bold">
									{% for message in messages%}
									<li >{{message}}</li>
									{%endfor%}
								</ul>
								{%endif%}
								<header><h2>Changer le mot de passe</h2></header>
								<form class="form-horizontal" method="POST">
									{% csrf_token %}
									{% for f in passform %}
									<div class="form-group">
										{{f.errors}}<br>
										<label for="id_{{f.name}}"><strong>{{f.label}}</strong></label>{{f}}
										<span class="helptext">{{f.help_text}}</span>
									</div>
									{%endfor%}
									<input type="submit" value="confirmer" name="pass_change" class="btn btn-dark active">
									</form>
									<hr>
								<header><h2>Changer l'email</h2></header>
								<form class="form-horizontal" method="POST">
									{%csrf_token%}
									{% for f in mailform %}
									<div class="form-group">
										{{f.errors}}<br>
										<label for="id_{{f.name}}"><strong>{{f.label}}</strong></label>{{f}}
										<span class="helptext">{{f.help_text}}</span>
									</div>
									{%endfor%}
									<input type="submit" value="confirmer" name="mail_change" class="btn btn-dark active">
									
								</form>
							</section>
						</div>
						
					</div>
				</div>	
			</div>


			<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="5u">
							<section id="box1">
								<header>
									<h2>Contact</h2>		
								</header>
								<ul class="style3">
									<li class="first">
										<p class="btn fa fa-envelope"> Envoyer un mail</p></li>
										<li class="first"><p class="fa btn fa-facebook"> Page facebook</a ></p>
									</li>
								</ul>
							</section>
						</div>
						<div class="3u">
							<section id="box2">
								<header>
									
								</header>
								<div> <a href="#" class="image full"><img src="" alt=""></a> </div>
							</section>
						</div>
						<div class="4u">
							<section id="box3">
								<header>
									<h2>articles externes</h2>
								</header>
								<ul class="style1">
									<li class="first"><a href="https://fr.malwarebytes.com/phishing/">Qu'est-ce que l'hameçonnage ? Types et exemples d'attaques par hameçonnage</a></li>
									<li><a href="https://www.kaspersky.fr/resource-center/definitions/spear-phishing">Qu'est-ce que le phishing ciblé ?</a></li>
								</ul>
							</section>
						</div>
					</div>
				</div>
			</div>
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
		<script src="{%static 'quiz/js/skel.min.js' %}"></script>
		<script src="{%static 'quiz/js/skel-panels.min.js' %}"></script>
		<script src="{%static 'quiz/js/init.js' %}"></script>
		<script type="text/JavaScript">	
			$(".errorlist").addClass("bg-danger text-white");
			$("#id_new_password1, #id_new_password2, #id_old_password,#id_new_email,#id_current_password").addClass("form-control");
			$('#id_old_mail').addClass("form-control-plaintext");
			$('#id_old_mail').attr('readonly','');
		</script>
	</body>
</html>

awarephish/quiz/templates/quiz/signin.html
{% load static%}<!DOCTYPE HTML>

<html>
	<head>
		<title>Connexion</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900' rel='stylesheet' type='text/css'>
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		
		<noscript>
			<link rel="stylesheet" href="{% static 'quiz/css/skel-noscript.css' %}" />
			<link rel="stylesheet" href="{% static 'quiz/css/style.css'%}" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
	</head>
	<body>
		<div id="wrapper">
			<!-- Header -->
			<div id="header">
				<div class="container"> 
					
					<!-- Logo -->
					<div id="logo">
						<h1><a href="{% url 'index'%}">AwarePhish</a></h1>
						<span class="font-weight-bolder">Pour ne pas tomber dans le piège !</span>
					</div>
					
					<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="{% url 'index'%}">page d'accueil</a></li>
							<li><a href="{% url 'conseils' %}">conseils</a></li>
							<li><a href={% if user.is_authenticated %}"{% url 'phishquiz' %}"{% else %}{% url 'signin' %} onclick="return confirm('Vous devez être connecté')"{% endif%}>testez-vous</a></li>
							<li>
								{% if user.is_authenticated %}
									<a href="{% url 'account' %}">Compte</a></li>
								{% else %}
									<a href="{% url 'signup' %}">S'inscrire</a>
								{% endif%}
							</li>
							<li class="active">
								{% if user.is_authenticated %}
									<a href="{% url 'signout' %}">Se déconnecter</a>
								{% else %}
									<a href="{% url 'signin' %}">Se connecter</a>
								{%endif%}
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /Header -->
			
			<div id="page">
				<div class="container">
					<div class="row">
						<div class="-2u skel-cell-important col-sm-10">
							<section >
								<header>
									<h2>Connexion</h2>
								</header>
								<div class="8u skel-cell-important">
									<form class="form-horizontal" method="POST">{% csrf_token %}
										
										<ul class="errorlist nonfield">
											<li>{{form.non_field_errors}}</li>
										</ul><br>
										
										{% for f in form %}
										<div class="form-group ">
											<label for="id_{{f.name}}"><strong>{{f.label}}</strong></label>{{f}}
										</div>
										{%endfor%}
									
										<input type="submit" value="Connexion" class="btn button btn-block btn-default"> 
										
									</form>
									
								</div>
							</section>
						</div>
					</div>
				</div>	
			</div>


			<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="5u">
							<section id="box1">
								<header>
									<h2>Contact</h2>		
								</header>
								<ul class="style3">
									<li class="first">
										<p class="btn fa fa-envelope"> Envoyer un mail</p></li>
										<li class="first"><p class="fa btn fa-facebook"> Page facebook</a ></p>
									</li>
								</ul>
							</section>
						</div>
						<div class="3u">
							<section id="box2">
								<header>
									
								</header>
								<div> <a href="#" class="image full"><img src="" alt=""></a> </div>
							</section>
						</div>
						<div class="4u">
							<section id="box3">
								<header>
									<h2>articles externes</h2>
								</header>
								<ul class="style1">
									<li class="first"><a href="https://fr.malwarebytes.com/phishing/">Qu'est-ce que l'hameçonnage ? Types et exemples d'attaques par hameçonnage</a></li>
									<li><a href="https://www.kaspersky.fr/resource-center/definitions/spear-phishing">Qu'est-ce que le phishing ciblé ?</a></li>
								</ul>
							</section>
						</div>
					</div>
				</div>
			</div>
		</div>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	<script src="{%static 'quiz/js/skel.min.js' %}"></script>
	<script src="{%static 'quiz/js/skel-panels.min.js' %}"></script>
	<script src="{%static 'quiz/js/init.js' %}"></script>
	
<script type="text/Javascript">
	$(".errorlist").addClass("bg-danger text-white");
	$("#id_username, #id_password").addClass("form-control");
</script>
	</body>
</html>